services:
  db:
    image: postgres:latest
    container_name: mi-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: desis
    ports:
      - "5433:5432"
    volumes:
      - ./datos:/var/lib/postgresql
  web:
    build: .
    container_name: mi-app-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db